version: '3.8'
services:
  db:
    image: ankane/pgvector:latest
    container_name: rag_movies_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: rag_movies
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

